# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_auto_20170622_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price_target',
            field=models.FloatField(),
        ),
    ]
