# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0003_auto_20170622_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stocks',
            field=models.ManyToManyField(to='stock_app.Stock'),
        ),
    ]
