# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0004_user_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price_target',
            field=models.FloatField(null=True),
        ),
    ]
